import Link from "next/link";
import { notFound } from "next/navigation";
import { getReceiptWithContext } from "@/lib/services/receipts";
import { formatCurrency } from "@/lib/money";
import { markSentAction } from "@/app/(app)/receipts/actions";
import { PrintButton } from "@/components/app/print-button";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";

export const runtime = "nodejs";

function detail(label: string, value: string, capitalize = false) {
  return (
    <div>
      <div className="text-xs text-muted-foreground">{label}</div>
      <div className={`font-medium tabular-nums${capitalize ? " capitalize" : ""}`}>
        {value}
      </div>
    </div>
  );
}

export default async function ReceiptPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  const ctx = await getReceiptWithContext(id);
  if (!ctx) notFound();
  const { receipt, payment, tenant, unit, property } = ctx;

  const currency = property?.currency ?? "USD";
  const voided = payment?.status === "voided";
  const addressParts = [
    property?.addressLine1,
    property?.addressLine2,
    [property?.city, property?.state, property?.zip].filter(Boolean).join(", "),
  ].filter(Boolean) as string[];
  const paidDate = receipt.paymentDate ?? payment?.paymentDate ?? null;
  const method = receipt.paymentMethod ?? payment?.method ?? null;
  const reference = payment?.referenceNumber ?? null;

  return (
    <div className="mx-auto max-w-2xl space-y-6">
      <div className="print-hidden flex flex-wrap items-center gap-2">
        <PrintButton />
        <form action={markSentAction} className="flex items-center gap-2">
          <input type="hidden" name="receiptId" value={receipt.id} />
          <select
            name="method"
            defaultValue="sms"
            className="h-9 rounded-md border bg-transparent px-3 text-sm capitalize"
          >
            <option value="sms">sms</option>
            <option value="email">email</option>
            <option value="printed">printed</option>
          </select>
          <Button type="submit" variant="outline">
            Mark sent
          </Button>
        </form>
        <Button variant="ghost" render={<Link href="/payments" />}>
          Back to payments
        </Button>
        {receipt.sentAt && (
          <span className="text-sm text-muted-foreground">
            Sent via {receipt.sentMethod} on {receipt.sentAt.toLocaleDateString()}
          </span>
        )}
      </div>

      <Card>
        <CardContent className="space-y-6 py-6">
          {voided && (
            <div className="rounded-md border border-destructive bg-destructive/10 px-4 py-2 text-center text-lg font-bold tracking-widest text-destructive">
              VOIDED
            </div>
          )}

          <div className="space-y-1 text-center">
            <h1 className="text-2xl font-semibold tracking-wide">RENT RECEIPT</h1>
            <p className="text-sm text-muted-foreground">{receipt.receiptNumber}</p>
          </div>

          <div className="space-y-0.5 text-center text-sm">
            <div className="font-medium">{property?.name ?? "—"}</div>
            {addressParts.map((line) => (
              <div key={line} className="text-muted-foreground">
                {line}
              </div>
            ))}
          </div>

          <div className="space-y-1 text-center">
            <div className="text-4xl font-bold tabular-nums">
              {formatCurrency(receipt.amountCents, currency)}
            </div>
            <div className="text-sm text-muted-foreground">Amount received</div>
          </div>

          <div className="grid grid-cols-2 gap-4 text-sm">
            {detail("Date paid", paidDate ? paidDate.toLocaleDateString() : "—")}
            {detail(
              "Tenant",
              tenant ? `${tenant.firstName} ${tenant.lastName}` : "—",
            )}
            {detail("Unit", unit ? unit.unitNumber : "—")}
            {detail(
              "Payment method",
              method ? method.replace(/_/g, " ") : "—",
              true,
            )}
            {reference && detail("Reference number", reference)}
            {detail(
              "Balance after payment",
              receipt.balanceAfterCents != null
                ? formatCurrency(receipt.balanceAfterCents, currency)
                : "—",
            )}
          </div>

          <div className="border-t pt-4 text-center text-xs text-muted-foreground">
            Receipt {receipt.receiptNumber} — generated by Property Manager
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
